
<div class="mod-add-game active" id="game-search">

    <div class="wrap">
        <form action="" class="game-search-form">
            <fieldset>
                <legend class="h h-2 center">Game Title</legend>
                <ul class="text-input game-search-bar">
                    <li><input type="search" class="input-inside game-search-input" /></li>
                </ul>
            </fieldset>
            <div class="game-search-results">
                <ul class="game-search-list">
                </ul>
            </div>
        </form>
    </div>

    <div class="add-game-tab-container">
        <a href="#" class="js-prevent-default add-game-tab h h-2">+ Add New Game +</a>
    </div>
</div>

<div class="wrap">

    <section class="games-wanted-section">
        <div class="center">
            <h1 class="h h-1">Games We Want</h1>
        </div>

        <div class="cover-flow" id="games-wanted">
            <div class="cover-flow-nav">
                <a href="#" class="cover-flow-arrow prev js-prevent-default">Previous</a>
                <a href="#" class="cover-flow-arrow next js-prevent-default">Next</a>
            </div>
            <ul class="cover-flow-carousel">
                <li class="cover-flow-item leftest">
                    <div class="cover-flow-container">
                        <h2 class="h h-3 center">Modern Warfare</h2>
                        <img src="assets/images/katamari-damacy.jpg" class="cover-flow-cover" />
                        <img src="assets/images/katamari-damacy.jpg" class="cover-flow-reflection" />
                    </div>
                </li>
                <li class="cover-flow-item">
                    <div class="cover-flow-container">
                        <h2 class="h h-3 center">Modern Warfare</h2>
                        <img src="assets/images/katamari-damacy.jpg" class="cover-flow-cover" />
                        <img src="assets/images/katamari-damacy.jpg" class="cover-flow-reflection" />
                    </div>
                </li>
                <li class="cover-flow-item">
                    <div class="cover-flow-container">
                        <h2 class="h h-3 center">Modern Warfare</h2>
                        <img src="assets/images/katamari-damacy.jpg" class="cover-flow-cover" />
                        <img src="assets/images/katamari-damacy.jpg" class="cover-flow-reflection" />
                    </div>
                </li>
                <li class="cover-flow-item">
                    <div class="cover-flow-container">
                        <h2 class="h h-3 center">Modern Warfare</h2>
                        <img src="assets/images/katamari-damacy.jpg" class="cover-flow-cover" />
                        <img src="assets/images/katamari-damacy.jpg" class="cover-flow-reflection" />
                    </div>
                </li>
                <li class="cover-flow-item rightest">
                    <div class="cover-flow-container">
                        <h2 class="h h-3 center">Modern Warfare</h2>
                        <img src="assets/images/katamari-damacy.jpg" class="cover-flow-cover" />
                        <img src="assets/images/katamari-damacy.jpg" class="cover-flow-reflection" />
                    </div>
                </li>
                <li class="cover-flow-item hidden rightest">
                    <div class="cover-flow-container">
                        <h2 class="h h-3 center">Modern Warfare</h2>
                        <img src="assets/images/katamari-damacy.jpg" class="cover-flow-cover" />
                        <img src="assets/images/katamari-damacy.jpg" class="cover-flow-reflection" />
                    </div>
                </li>
            </ul>
        </div>
    </section>

</div>